#!/bin/bash
#alternate user interface designed by zigbert.
#120203 rodin.s: internationalized.
#120224 more gettext's required. icons were missing.
#120224 handle translated help.htm
#120225 fix for translated categories.
#120504 some files moved into /tmp/petget
#120508 01micko: bugfix. ref: http://murga-linux.com/puppy/viewtopic.php?p=625843#625843
#120515 calls to /tmp/petget/filterpkgs.results.postfilter.sh replace by /usr/local/petget/postfilterpkgs.sh.
#120529 app icons in tree. variable FLG_APPICONS created in pkg_chooser.sh
#120811 category field now supports sub-category |category;subcategory|, use as icon in ppm main window.
#130330 GUI filter. see also filterpkgs.sh, pkg_chooser.sh, ui_Ziggy.
#130331 more GUI filter options.

export TEXTDOMAIN=petget___ui_Ziggy
export OUTPUT_CHARSET=UTF-8

echo -n > /tmp/pkgs_to_install
echo 0 > /tmp/petget/install_status_percent
echo "" > /tmp/petget/install_status

ALLITEM='' ; ALLSTOCK='' ; CATHEIGHT='100' ; WINHEIGHT='420'
if [ "$ALLCATEGORY" != "" ];then
 ALLITEM="<item stock=\"gtk-ALL\">$(gettext 'All')|All</item>"
 ALLSTOCK='stock["gtk-ALL"] = {{ "pet24.png", *, *, *}}'
 CATHEIGHT='112'
 WINHEIGHT='428'
fi

touch /var/local/petget/bb_category
if [ "`cat /var/local/petget/bb_category`" = "true" ]; then
  BBITEM="<item stock=\"gtk-BB\">$(gettext 'BuildingBlock')|BuildingBlock</item>"
else
  BBITEM=""
fi

#120224 handle translated help.htm
LANG1="${LANG%_*}" #ex: de
HELPFILE="/usr/local/petget/help.htm"
[ -f /usr/local/petget/help-${LANG1}.htm ] && HELPFILE="/usr/local/petget/help-${LANG1}.htm"

DEFGUIFILTER="$(cat /var/local/petget/gui_filter)" #130330 see pkg_chooser.sh, and below.


kill_check (){
	TMP="`ps -eo pid,command`"
	for I in `grep -F findmissingpkgs <<< "$TMP" | awk '{print $1}' `; do kill -9 $I; done
	for I in `grep -F dependencies <<< "$TMP" | awk '{print $1}' `; do kill -9 $I; done
	for I in `grep -F check_total_size <<< "$TMP" | grep -vF rxvt | awk '{print $1}' `; do kill -9 $I; done
	for I in `grep -F installed_size_preview <<< "$TMP" | awk '{print $1}' `; do kill -9 $I; done
}

add_item (){
	kill_check
	[ ! "$(grep -F $TREE1 /tmp/pkgs_to_install)" ] && echo "$(grep -F $TREE1 /tmp/petget/filterpkgs.results.post)" >> /tmp/pkgs_to_install
	/usr/local/petget/installwindow.sh check_total_size &
}

remove_item (){
	kill_check
	if [ "$TREE_INSTALL" ]; then
		grep -v "$TREE_INSTALL" /tmp/pkgs_to_install > /tmp/pkgs_to_install2
		mv -f /tmp/pkgs_to_install2 /tmp/pkgs_to_install
	fi
	touch /tmp/install_pets_quietly #avoid splashes
	/usr/local/petget/installwindow.sh check_total_size &
}
export -f kill_check add_item remove_item


#130330 $GUIONLYSTR $ANYTYPESTR are exported from pkg_chooser.sh.  130331 also $GUIEXCSTR $NONGUISTR
export MAIN_DIALOG='<window title="'$(gettext 'Puppy Package Manager')'" width-request="750" icon-name="gtk-about" default_height="'${WINHEIGHT}'">
<vbox space-expand="true" space-fill="true">
  <vbox space-expand="true" space-fill="true">
    <vbox space-expand="false" space-fill="false">
      <hbox spacing="1" space-expand="true" space-fill="true">
        <button tooltip-text="'$(gettext 'Quit package manager')'" space-expand="false" space-fill="false">
          '"`/usr/lib/gtkdialog/xml_button-icon quit`"'
          <action>exit:EXIT</action>
        </button>
        <button tooltip-text="'$(gettext 'Help')'" space-expand="false" space-fill="false">
          '"`/usr/lib/gtkdialog/xml_button-icon help`"'
          <action>defaulthtmlviewer file://'${HELPFILE}' & </action>
        </button>
        <button tooltip-text="'$(gettext 'Configure package manager')'" space-expand="false" space-fill="false">
          '"`/usr/lib/gtkdialog/xml_button-icon preferences`"'
          <action>/usr/local/petget/configure.sh</action>
          <action>/usr/local/petget/filterpkgs.sh</action>
          <action>refresh:TREE1</action>
        </button>
        <button tooltip-text="'$(gettext 'Uninstall packages')'" space-expand="false" space-fill="false">
          <label>" '$(gettext 'Uninstall')' "</label>
          '"`/usr/lib/gtkdialog/xml_button-icon package_remove`"'
          <action>launch:INSTALLED_DIALOG</action>
        </button>
      
        <text space-expand="true" space-fill="true"><label>""</label></text>

        <entry width-request="80" activates-default="true" is-focus="true" secondary-icon-stock="gtk-find">
          <variable>ENTRY1</variable>
          <action signal="activate">/usr/local/petget/findnames.sh all</action>
          <action signal="activate">refresh:TREE1</action>
          <action signal="activate">/usr/local/petget/show_installed_version_diffs.sh & </action>
          <action signal="secondary-icon-release">/usr/local/petget/findnames.sh all</action>
          <action signal="secondary-icon-release">refresh:TREE1</action>
          <action signal="secondary-icon-release">/usr/local/petget/show_installed_version_diffs.sh & </action>
        </entry>
      
        <text space-expand="true" space-fill="true"><label>""</label></text>

        <hbox space-expand="false" space-fill="false">
          <comboboxtext width-request="150" space-expand="false" space-fill="false">
            <variable>INSTALL_MODE</variable>
            <item>'$(gettext 'Auto install')'</item>
            <item>'$(gettext 'Step by step installation (classic mode)')'</item>
            <item>'$(gettext 'Download packages (no install)')'</item>
            <item>'$(gettext 'Download all (packages and dependencies)')'</item>
          </comboboxtext>
          <button space-expand="false" space-fill="false">
            '"`/usr/lib/gtkdialog/xml_button-icon package_add`"'
            <label>" '$(gettext 'Install')' "</label>
            <action>kill_check</action>
            <action>disable:VBOX_MAIN</action>
            <action>cut -d"|" -f1,4 /tmp/pkgs_to_install > /tmp/pkgs_to_install_tmp; mv -f /tmp/pkgs_to_install_tmp /tmp/pkgs_to_install</action>
            <action>/usr/local/petget/installwindow.sh "$INSTALL_MODE" &</action>
          </button> 
          <sensitive>false</sensitive>
          <variable>HBOX_INSTALL</variable>
        </hbox>
      </hbox>
    </vbox>

    <hbox space-expand="true" space-fill="true">
      <hbox space-expand="false" space-fill="false">
        <vbox space-expand="true" space-fill="true">
          <frame '$(gettext 'Repositories')'>
            <vbox scrollable="true" shadow-type="0" hscrollbar-policy="2" space-expand="true" space-fill="true">
              '${DB_ORDERED}'
              <text height-request="1" space-expand="true" space-fill="true"><label>""</label></text>
              <height>128</height>
              <width>50</width>
            </vbox>
          </frame>
          <vbox space-expand="false" space-fill="false">
            <frame '$(gettext 'package types')'>
              <hbox>
                <vbox>
                  <checkbox>
                    <default>'${DEF_CHK_EXE}'</default>
                    <label>EXE</label>
                    <variable>CHK_EXE</variable>
                    <action>/usr/local/petget/postfilterpkgs.sh EXE $CHK_EXE</action>
                    <action>refresh:TREE1</action>
                  </checkbox>
                  <checkbox>
                    <default>'${DEF_CHK_DEV}'</default>
                    <label>DEV</label>
                    <variable>CHK_DEV</variable>
                    <action>/usr/local/petget/postfilterpkgs.sh DEV $CHK_DEV</action>
                    <action>refresh:TREE1</action>
                  </checkbox>
                  <checkbox>
                    <default>'${DEF_CHK_DOC}'</default>
                    <label>DOC</label>
                    <variable>CHK_DOC</variable>
                    <action>/usr/local/petget/postfilterpkgs.sh DOC $CHK_DOC</action>
                    <action>refresh:TREE1</action>
                  </checkbox>
                  <checkbox>
                    <default>'${DEF_CHK_NLS}'</default>
                    <label>NLS</label>
                    <variable>CHK_NLS</variable>
                    <action>/usr/local/petget/postfilterpkgs.sh NLS $CHK_NLS</action>
                    <action>refresh:TREE1</action>
                  </checkbox>
                </vbox>
                <hbox space-expand="true" space-fill="true">
                  <vbox space-expand="false" space-fill="false">
                    <comboboxtext width-request="120">
                      <variable>FILTERCOMBOBOX</variable>
                      <default>'$DEFGUIFILTER'</default>
                      <item>'$ANYTYPESTR'</item>
                      <item>'$GUIONLYSTR'</item>
                      <item>GTK+2 '$GUIONLYSTR'</item>
                      <item>GTK+3 '$GUIONLYSTR'</item>
                      <item>Qt4 '$GUIONLYSTR'</item>
                      <item>Qt4 '$GUIEXCSTR' KDE</item>
                      <item>Qt5 '$GUIONLYSTR'</item>
                      <item>Qt5 '$GUIEXCSTR' KDE</item>
                      <item>'$NONGUISTR'</item>
                      <action>echo -n "$FILTERCOMBOBOX" > /var/local/petget/gui_filter</action>
                      <action>/usr/local/petget/filterpkgs.sh</action>
                      <action>refresh:TREE1</action>
                    </comboboxtext>
                  </vbox>
                </hbox>
              </hbox>
            </frame>
          </vbox>
        </vbox>  
      </hbox>

      <vbox space-expand="true" space-fill="true">
        <hbox spacing="1" space-expand="true" space-fill="true">
          <hbox space-expand="false" space-fill="false">
            <tree name="category" selected-row="0" exported_column="1" column-visible="true|false" space-expand="false" space-fill="false">
              <label>'$(gettext 'Category')'|command</label>
              <variable>CATEGORY</variable>
              <item stock="gtk-Desktop">'$(gettext 'Desktop')'|Desktop</item>
              <item stock="gtk-System">'$(gettext 'System')'|System</item>
              <item stock="gtk-Setup">'$(gettext 'Setup')'|Setup</item>
              <item stock="gtk-Utility">'$(gettext 'Utility')'|Utility</item>
              <item stock="gtk-Filesystem">'$(gettext 'Filesystem')'|Filesystem</item>
              <item stock="gtk-Graphic">'$(gettext 'Graphic')'|Graphic</item>
              <item stock="gtk-Document">'$(gettext 'Document')'|Document</item>
              <item stock="gtk-Business">'$(gettext 'Business')'|Business</item>
              <item stock="gtk-Personal">'$(gettext 'Personal')'|Personal</item>
              <item stock="gtk-Network">'$(gettext 'Network')'|Network</item>
              <item stock="gtk-Internet">'$(gettext 'Internet')'|Internet</item>
              <item stock="gtk-Multimedia">'$(gettext 'Multimedia')'|Multimedia</item>
              <item stock="gtk-Fun">'$(gettext 'Fun')'|Fun</item>
              '${BBITEM}'
              '${ALLITEM}'
              <width>140</width><height>'${CATHEIGHT}'</height>
              <action signal="changed">/usr/local/petget/filterpkgs.sh $CATEGORY</action>
              <action signal="changed">refresh:TREE1</action>
            </tree>
          </hbox>
          <hbox space-expand="true" space-fill="true">
            <tree column-resizeable="true|false" space-expand="true" space-fill="true">
              <label>'$(gettext 'Package|Description')'</label>
              <variable>TREE1</variable>
              <width>210</width>
              <input file icon-column="1">/tmp/petget/filterpkgs.results.post</input>
              <action signal="button-release-event">add_item $TREE1</action>
              <action signal="button-release-event">refresh:TREE_INSTALL</action>
              <action signal="button-release-event">enable:HBOX_INSTALL</action>
            </tree>
          </hbox>
          <hbox space-expand="true" space-fill="true">
            <tree hscrollbar-policy="1" column-visible="true|false|true" tooltip-text="'$(gettext 'Remove item from list by click on it')'" space-expand="false" space-fill="false">
              <label>'$(gettext 'Packages to install')'|'$(gettext 'Description')'|'$(gettext 'Repository')'</label>
              <variable>TREE_INSTALL</variable>
              <input file icon-column="1">/tmp/pkgs_to_install</input>
              <width>160</width>
              <action signal="button-release-event">remove_item $TREE_INSTALL</action>
              <action signal="button-release-event">refresh:TREE_INSTALL</action>
            </tree>
          </hbox>
        </hbox>
      </vbox>
    </hbox>
    <variable>VBOX_MAIN</variable>
  </vbox>
  <hbox space-expand="false" space-fill="false">
    <progressbar height-request="25" space-expand="true" space-fill="true">
      <input>while [ -s /tmp/petget/install_status ]; do cat /tmp/petget/install_status_percent; cat /tmp/petget/install_status; sleep 0.3; done</input>
      <action>enable:VBOX_MAIN</action>
      <action>disable:HBOX_INSTALL</action>
      <action>rm /tmp/pkgs_to_install</action>
      <action>refresh:TREE_INSTALL</action>
      <action>/usr/local/petget/filterpkgs.sh</action>
      <action>refresh:TREE1</action>
      <action>/usr/local/petget/finduserinstalledpkgs.sh</action>
      <action>refresh:TREE2</action>
      <action>echo 0 > /tmp/petget/install_status_percent</action>
      <action>echo "" > /tmp/petget/install_status</action>
    </progressbar>
    '"`/usr/lib/gtkdialog/xml_scalegrip`"'
  </hbox>
</vbox>
<action signal="delete-event">rm /tmp/pkgs_to_install</action>
<action signal="delete-event">rm /tmp/petget/install_status</action>
</window>'




export INSTALLED_DIALOG='<window title="'$(gettext 'Uninstall Puppy Package')'" icon-name="gtk-about">
<vbox space-expand="true" space-fill="true">
  '"`/usr/lib/gtkdialog/xml_info fixed package_remove.svg 60 "$(gettext "Uninstall programs from your system. Select program(s) and click the Remove-button.")"`"'
  <vbox space-expand="true" space-fill="true">
    <tree rubber-banding="true" selection-mode="3" space-expand="true" space-fill="true">
      <label>'$(gettext 'Installed Package|Description')'</label>
      <height>300</height>
      <width>450</width>
      <variable>TREE2</variable>
      <input file icon-column="1">/tmp/petget/installedpkgs.results.post</input>
    </tree>
  </vbox>
  <hbox space-expand="false" space-fill="false">
    <comboboxtext>
      <variable>REMOVE_MODE</variable>
      <item>'$(gettext 'Auto remove')'</item>
      <item>'$(gettext 'Step by step remove (classic mode)')'</item>
    </comboboxtext>
    <button space-expand="false" space-fill="false">
      '"`/usr/lib/gtkdialog/xml_button-icon package_remove`"'
      <label>" '$(gettext 'Remove package')' "</label>
      <action>echo "$TREE2" > /tmp/pkgs_to_remove; /usr/local/petget/removewindow.sh "$REMOVE_MODE"</action>
      <action>refresh:TREE2</action>
      <action>/usr/local/petget/filterpkgs.sh $CATEGORY</action>
      <action>refresh:TREE1</action>
    </button>
    '"`/usr/lib/gtkdialog/xml_scalegrip`"'
  </hbox>
</vbox>
</window>' 

mkdir -p /tmp/puppy_package_manager
ln -s /usr/local/lib/X11/pixmaps/*48.png /tmp/puppy_package_manager 2>/dev/null
echo '
style "category" {
	font_name="bold" }
widget "*category" style "category"

style "bg_report" {
	bg[NORMAL]="#222" }
widget "*bg_report" style "bg_report"

style "status_bar" {
	font_name="normal 8" }
widget_class "*.GtkStatusbar*" style "status_bar"

style "icon-style" {
	GtkStatusbar::shadow_type	= GTK_SHADOW_NONE

	stock["gtk-Desktop"]  = {{ "x48.png", *, *, *}}
	stock["gtk-System"]	  = {{ "pc48.png", *, *, *}}
	stock["gtk-Setup"]    = {{ "configuration48.png", *, *, *}}
	stock["gtk-Utility"]  = {{ "utility48.png", *, *, *}}
	stock["gtk-Filesystem"] = {{ "folder48.png", *, *, *}}
	stock["gtk-Graphic"]  = {{ "paint48.png", *, *, *}}
	stock["gtk-Document"] = {{ "word48.png", *, *, *}}
	stock["gtk-Business"] = {{ "spread48.png", *, *, *}}
	stock["gtk-Personal"] = {{ "date48.png", *, *, *}}
	stock["gtk-Network"]  = {{ "connect48.png", *, *, *}}
	stock["gtk-Internet"] = {{ "www48.png", *, *, *}}
	stock["gtk-Multimedia"] = {{ "multimedia48.png", *, *, *}}
	stock["gtk-Fun"]      = {{ "games48.png", *, *, *}}
	stock["gtk-BB"]       = {{ "pet48.png", *, *, *}}
	'${ALLSTOCK}'}
class "GtkWidget" style "icon-style"' > /tmp/puppy_package_manager/gtkrc_ppm

export GTK2_RC_FILES=/root/.gtkrc-2.0:/tmp/puppy_package_manager/gtkrc_ppm
. /usr/lib/gtkdialog/xml_info gtk #build bg_pixmap for gtk-theme
